### ISSUE TITLE
Error code 10197: No market data during competing live session

### ISSUE THREAD

**Issue by WoodWorker49** [quantverse/ptltrader#1]
Hello @quantverse 

First of all, thank you for your dedication and that great project.

I've installed the PTL trader, open my TWS, linked the two, but I am getting the following error message:
`Error code 10197 No market data during competing live session`

I guess it should not be happening, since TWS must be open when trading:

![image](https://user-images.githubusercontent.com/109142956/178538358-316286d9-6519-4d5b-ad03-5b9986bb6575.png)

I'm using the v1.6.0.

Regards

**Comment by quantverse** [comment]
Hi,

the error message is forwarded from IB API itself, you will have to consult the IB what it does mean. It is marked as a notice so maybe it does not mean anything serious I guess...

**Comment by WoodWorker49** [comment]
Noted with Thanks!
